require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/CaseEquality:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/ModuleFunction:
  Enabled: false
